name: build
on: [push]
jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: StyLua
        uses: JohnnyMorganz/stylua-action@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          version: 'v0.2.7'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate standard library
        run: selene generate-roblox-std
      - name: Run Selene
        run: selene src
  
